apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: note-mongo
  name: note-mongo
spec:
  type: NodePort
  ports:
  - name: "27017"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    service: note-mongo
status:
  loadBalancer: {}
