apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: note-java
  name: note-java
spec:
  ports:
  - name: "50052"
    port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    service: note-java
status:
  loadBalancer: {}
