apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-mongo
    spec:
      containers:
      - image: mongo
        name: note-mongo
        # volumeMounts:
        # - name: mongo-persistent-storage
        #   mountPath: /data/db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
      restartPolicy: Always
      # volumes:
      # - name: mongo-persistent-storage
      #   hostPath:
      #     path: /tmp/mongodb
status: {}
