apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-java
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-java
    spec:
      containers:
      - image: raymondfeng/note-java:istio
        name: note-java
        ports:
        - containerPort: 50052
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: note-java
  name: note-java
spec:
  ports:
  - name: grpc-java
    port: 50052
    protocol: TCP
    targetPort: 50052
  selector:
    service: note-java
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-loopback
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-loopback
    spec:
      containers:
      - image: raymondfeng/note-loopback:istio
        name: note-loopback
        ports:
        - containerPort: 50051
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: note-loopback
  name: note-loopback
spec:
  type: NodePort
  ports:
  - name: grpc-node
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: http-node
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    service: note-loopback
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-mongo
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-mongo
    spec:
      containers:
      - image: mongo
        name: note-mongo
        # volumeMounts:
        # - name: mongo-persistent-storage
        #   mountPath: /data/db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
      restartPolicy: Always
      # volumes:
      # - name: mongo-persistent-storage
      #   hostPath:
      #     path: /tmp/mongodb
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: note-mongo
  name: note-mongo
spec:
  type: NodePort
  ports:
  - name: tcp-mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    service: note-mongo
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-swift
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-swift
    spec:
      containers:
      - image: raymondfeng/note-swift:istio
        name: note-swift
        ports:
        - containerPort: 50053
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: note-swift
  name: note-swift
spec:
  ports:
  - name: grpc-swift
    port: 50053
    protocol: TCP
    targetPort: 50053
  selector:
    service: note-swift
status:
  loadBalancer: {}
---
