apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-java
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-java
    spec:
      containers:
      - image: raymondfeng/note-java
        name: note-java
        ports:
        - containerPort: 50052
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
