apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-loopback
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-loopback
    spec:
      containers:
      - image: raymondfeng/note-loopback
        name: note-loopback
        ports:
        - containerPort: 50051
          protocol: TCP
        - containerPort: 3000
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
