apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: note-loopback
  name: note-loopback
spec:
  type: NodePort
  ports:
  - name: "50051"
    port: 50051
    protocol: TCP
    targetPort: 50051
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    service: note-loopback
status:
  loadBalancer: {}
