apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: note-swift
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: note-swift
    spec:
      containers:
      - image: raymondfeng/note-swift
        name: note-swift
        ports:
        - containerPort: 50053
          protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
